### ISSUE TITLE
Fix the Affective Motion Graph Data

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#15]
As discussed before.

**Comment by subirranjan1** [comment]
Yes, I am looking into this and will update asap.

**Comment by subirranjan1** [comment]
Hi @omimo  @michaelnixon 

Please find below my investigation:-
1. There were some problems in the excel itself which I believe have been resolved. Will check later if there are more.
2. Need to check  the folder containing all the files whether we are missing some files.As of now updated excel looks fine to me.
3. In case where @omimo  wanted to display records twice both for Sean and Meridith when the file name is(ex: HVHA_Free_Improv1_meredith_sean.MOV) , I found that logic in our database does not support that.
  --Presently new excel sheet contains two rows for the above file name(one for Sean and other for Meridith) but after importing csv,  data_tracks table contain only one row and creates an association in data_tracks_movers table for both the movers.This is why records get skewed and appear lesser than in CSV.

I assume for that we will have to modify logic of the database, however I would like @michaelnixon advice on that.Please find attached screenshot for reference.

Feel free to question me in case I don't make sense.

![csv](https://cloud.githubusercontent.com/assets/1945796/12087769/93b2d0ba-b28a-11e5-8235-e4b0820d7b93.png)
![data_tracks](https://cloud.githubusercontent.com/assets/1945796/12087770/93b9c000-b28a-11e5-9313-80d45f6da790.png)
![data_tracks_movers](https://cloud.githubusercontent.com/assets/1945796/12087771/93bb307a-b28a-11e5-9430-411fceea5f4d.png)
![screenshot from 2016-01-04 02-25-59](https://cloud.githubusercontent.com/assets/1945796/12087772/93bc6206-b28a-11e5-9b37-2229ee1eb13f.png)

**Comment by omimo** [comment]
Hello!

Thanks for the update Subir.

Regarding 1 and 2, have you updated the database? Because I still see the wrong entries.

Regarding 3,  let's hear from @michaelnixon.

Cheers,
Omid

**Comment by subirranjan1** [comment]
@omimo  I have updated the data in the development environment.I can pass on the new excel for you to verify if you want.

**Comment by omimo** [comment]
That works. You can also just put everyting online, that way iit s easier to check them.

**Comment by subirranjan1** [comment]
@omimo Did you mean, should I upload the excel on the portal? If Yes, then I will create a separate menu for that tonight. @michaelnixon  A quick question.. how do I reimport the data in the production db for just one project without affecting the other projects? In development I dropped->created->migrated->batch import the csv file which obviously impacts other projects.  Should I rake batch:import["new filename"] RAILS_ENV="production"  ? Will it overwrite the existing data or what? Please let me know because I am not sure how to proceed for this.

**Comment by michaelnixon** [comment]
To import...
Run the rake command from the root folder of the app. The first argument is the path to the csv file. The second argument is whether the method should reupload files -- this is for efficiency if you're running it to fix metadata issues rather than file issues. The final argument goes to rake, not to the method, and indicates the environment to perform it in. Keep in mind that the production server can technically have a development environment, just as your development server (i.e. your PC) can have a production environment, so make sure you set this appropriately.

Sample command:
rake batch:import["import-format_MS_EXPERIMENT_Final_v7.csv","false"] RAILS_ENV="production"

The import method in data_track.rb is globally non-destructive and won't affect any other projects etc. In other words, it doesn't "wipe out" anything before beginning to run.

**Comment by michaelnixon** [comment]
Regarding re-using the same file:
The database will support this just fine, however, I didn't accommodate this in the import method, since I wasn't made aware of the possibility. 
See data_track.rb line ~112:  
`track = DataTrack.find_by_name(row['data_track_name']) || DataTrack.create(name: row['data_track_name'])`
Here, I check whether a DataTrack object with the same name has been uploaded already, and use it if so. This allows us to re-run the import process without creating duplicate objects. Since it grabs that track, it then resets all the data to the current row in the CSV, meaning that the last such row will be the owner and info that "sticks".

My belief was that the name of the data track would be meaningful metadata, not just the file name repeated, since that's redundant busy-work for everyone -- we could have extracted that from the file. This leads to me using the name as a unique identifier. 

If you don't want DataTrack names to be unique, then you'll have to change the import code. I think the solution is to break this into multiple lines. First, find the Take with the appropriate name. Then, find the DataTrack within it with the correct characteristics (correct name AND correct mover etc).

At any point that I currently use the logic of finding an object by name, if you determine that users need to be able to use NON-UNIQUE names, you will need to modify this logic.

**Comment by subirranjan1** [comment]
@omimo  Please check email. I will modify the logic as per Michael post your confirmation.

**Comment by subirranjan1** [comment]
@omimo  Affective Motion Graph Data is fixed. Please verify and comment. Waiting for @michaelnixon  to comment on #34 regarding populating of asset table which will solve download function for this project.
